# Generated by Django 5.0.2 on 2024-02-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contactA',
            new_name='acontact',
        ),
    ]
